### ISSUE TITLE
Typo in the doc

### ISSUE THREAD

**Issue by alexisflesch** [jobh/latex.py#1]
In the doc you write _python parse.py_ where you mean _python latex.py_, I guess you changed the name of your program at some point.

Anyhow, thanks a lot ! I've been looking for a program like this to pre-process user-defined macros and you script seems to be doing the job just fine.

**Comment by jobh** [comment]
Thanks for the feedback! I haven't looked at this code in many years, I am pleasantly surprised it still works (and that it is still useful).
